// Mocks generated by Mockito 5.4.4 from annotations
// in hypnosis_downloads/test/test_environment.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i11;
import 'dart:isolate' as _i12;

import 'package:audio_session/audio_session.dart' as _i20;
import 'package:authentication_logic/authentication_logic.dart' as _i3;
import 'package:connectivity_plus/connectivity_plus.dart' as _i21;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i22;
import 'package:dio/dio.dart' as _i6;
import 'package:flutter_downloader/flutter_downloader.dart' as _i14;
import 'package:hive_flutter/hive_flutter.dart' as _i2;
import 'package:hypnosis_downloads/library/data/model/product.dart' as _i13;
import 'package:hypnosis_downloads/library/data/model/product_pack.dart'
    as _i16;
import 'package:hypnosis_downloads/library/data/model/session.dart' as _i7;
import 'package:hypnosis_downloads/library/data/sessions_repository.dart'
    as _i15;
import 'package:hypnosis_downloads/playlists/data/model/playlist.dart' as _i8;
import 'package:hypnosis_downloads/playlists/data/playlists_repository.dart'
    as _i17;
import 'package:hypnosis_downloads/products/audios/download/data/downloadable_products_repository.dart'
    as _i10;
import 'package:hypnosis_downloads/products/audios/download/data/model/downloadable.dart'
    as _i5;
import 'package:hypnosis_downloads/products/data/products_repository.dart'
    as _i18;
import 'package:just_audio/just_audio.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCurrentUser_1 extends _i1.SmartFake implements _i3.CurrentUser {
  _FakeCurrentUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCurrentUserRepository_2 extends _i1.SmartFake
    implements _i3.CurrentUserRepository {
  _FakeCurrentUserRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamController_3<T> extends _i1.SmartFake
    implements _i4.StreamController<T> {
  _FakeStreamController_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownloadable_4<T> extends _i1.SmartFake
    implements _i5.Downloadable<T> {
  _FakeDownloadable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i6.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_6 extends _i1.SmartFake implements _i7.Session {
  _FakeSession_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylist_7 extends _i1.SmartFake implements _i8.Playlist {
  _FakePlaylist_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaybackEvent_8 extends _i1.SmartFake implements _i9.PlaybackEvent {
  _FakePlaybackEvent_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_9 extends _i1.SmartFake implements Duration {
  _FakeDuration_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_10 extends _i1.SmartFake implements _i9.PlayerState {
  _FakePlayerState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CurrentUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentUserRepository extends _i1.Mock
    implements _i3.CurrentUserRepository {
  @override
  _i2.Box<_i3.CurrentUser> get currentUserBox => (super.noSuchMethod(
        Invocation.getter(#currentUserBox),
        returnValue: _FakeBox_0<_i3.CurrentUser>(
          this,
          Invocation.getter(#currentUserBox),
        ),
        returnValueForMissingStub: _FakeBox_0<_i3.CurrentUser>(
          this,
          Invocation.getter(#currentUserBox),
        ),
      ) as _i2.Box<_i3.CurrentUser>);

  @override
  _i3.CurrentUser get currentUser => (super.noSuchMethod(
        Invocation.getter(#currentUser),
        returnValue: _FakeCurrentUser_1(
          this,
          Invocation.getter(#currentUser),
        ),
        returnValueForMissingStub: _FakeCurrentUser_1(
          this,
          Invocation.getter(#currentUser),
        ),
      ) as _i3.CurrentUser);

  @override
  _i4.Stream<_i3.CurrentUser> get currentUserStream => (super.noSuchMethod(
        Invocation.getter(#currentUserStream),
        returnValue: _i4.Stream<_i3.CurrentUser>.empty(),
        returnValueForMissingStub: _i4.Stream<_i3.CurrentUser>.empty(),
      ) as _i4.Stream<_i3.CurrentUser>);

  @override
  void set(_i3.CurrentUser? user) => super.noSuchMethod(
        Invocation.method(
          #set,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> update({String? name}) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#name: name},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void deleteCurrentUser() => super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoginWithEmailPasswordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithEmailPasswordRepository extends _i1.Mock
    implements _i3.LoginWithEmailPasswordRepository {
  @override
  _i4.Future<_i3.CurrentUser> loginWithEmailPassword(
    String? email,
    String? password,
    bool? remember,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmailPassword,
          [
            email,
            password,
            remember,
          ],
        ),
        returnValue: _i4.Future<_i3.CurrentUser>.value(_FakeCurrentUser_1(
          this,
          Invocation.method(
            #loginWithEmailPassword,
            [
              email,
              password,
              remember,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.CurrentUser>.value(_FakeCurrentUser_1(
          this,
          Invocation.method(
            #loginWithEmailPassword,
            [
              email,
              password,
              remember,
            ],
          ),
        )),
      ) as _i4.Future<_i3.CurrentUser>);

  @override
  void forceToThrowExceptionIfFailed(_i6.Response<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #forceToThrowExceptionIfFailed,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RestorePasswordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestorePasswordRepository extends _i1.Mock
    implements _i3.RestorePasswordRepository {
  @override
  _i4.Future<void> restorePasswordVia(String? email) => (super.noSuchMethod(
        Invocation.method(
          #restorePasswordVia,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void forceToThrowExceptionIfFailed(_i6.Response<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #forceToThrowExceptionIfFailed,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LogoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutRepository extends _i1.Mock implements _i3.LogoutRepository {
  @override
  _i3.CurrentUserRepository get currentUserRepository => (super.noSuchMethod(
        Invocation.getter(#currentUserRepository),
        returnValue: _FakeCurrentUserRepository_2(
          this,
          Invocation.getter(#currentUserRepository),
        ),
        returnValueForMissingStub: _FakeCurrentUserRepository_2(
          this,
          Invocation.getter(#currentUserRepository),
        ),
      ) as _i3.CurrentUserRepository);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DownloadableProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadableProductsRepository extends _i1.Mock
    implements _i10.DownloadableProductsRepository {
  @override
  set savedDir(_i11.Directory? _savedDir) => super.noSuchMethod(
        Invocation.setter(
          #savedDir,
          _savedDir,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set port(_i12.ReceivePort? _port) => super.noSuchMethod(
        Invocation.setter(
          #port,
          _port,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.StreamController<dynamic> get listener => (super.noSuchMethod(
        Invocation.getter(#listener),
        returnValue: _FakeStreamController_3<dynamic>(
          this,
          Invocation.getter(#listener),
        ),
        returnValueForMissingStub: _FakeStreamController_3<dynamic>(
          this,
          Invocation.getter(#listener),
        ),
      ) as _i4.StreamController<dynamic>);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<dynamic> startReceivingDownloadStatus() => (super.noSuchMethod(
        Invocation.method(
          #startReceivingDownloadStatus,
          [],
        ),
        returnValue: _i4.Stream<dynamic>.empty(),
        returnValueForMissingStub: _i4.Stream<dynamic>.empty(),
      ) as _i4.Stream<dynamic>);

  @override
  void stopReceivingDownloadStatus() => super.noSuchMethod(
        Invocation.method(
          #stopReceivingDownloadStatus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i5.Downloadable<_i13.Product>>> getDownloadStatusFor(
          List<_i13.Product>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadStatusFor,
          [products],
        ),
        returnValue: _i4.Future<List<_i5.Downloadable<_i13.Product>>>.value(
            <_i5.Downloadable<_i13.Product>>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.Downloadable<_i13.Product>>>.value(
                <_i5.Downloadable<_i13.Product>>[]),
      ) as _i4.Future<List<_i5.Downloadable<_i13.Product>>>);

  @override
  _i4.Future<_i5.Downloadable<_i13.Product>> getDownloadStatusForSingle(
          _i13.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDownloadStatusForSingle,
          [product],
        ),
        returnValue: _i4.Future<_i5.Downloadable<_i13.Product>>.value(
            _FakeDownloadable_4<_i13.Product>(
          this,
          Invocation.method(
            #getDownloadStatusForSingle,
            [product],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Downloadable<_i13.Product>>.value(
                _FakeDownloadable_4<_i13.Product>(
          this,
          Invocation.method(
            #getDownloadStatusForSingle,
            [product],
          ),
        )),
      ) as _i4.Future<_i5.Downloadable<_i13.Product>>);

  @override
  _i4.Future<String?> requestDownload(
          _i5.Downloadable<_i13.Product>? downloadable) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDownload,
          [downloadable],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> pauseDownload(
          _i5.Downloadable<_i13.Product>? downloadable) =>
      (super.noSuchMethod(
        Invocation.method(
          #pauseDownload,
          [downloadable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelDownload(
          _i5.Downloadable<_i13.Product>? downloadable) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [downloadable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> resumeDownload(
          _i5.Downloadable<_i13.Product>? downloadable) =>
      (super.noSuchMethod(
        Invocation.method(
          #resumeDownload,
          [downloadable],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> retryDownload(
          _i5.Downloadable<_i13.Product>? downloadable) =>
      (super.noSuchMethod(
        Invocation.method(
          #retryDownload,
          [downloadable],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> delete(_i5.Downloadable<_i13.Product>? downloadable) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [downloadable],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i14.DownloadTask? getTaskOf(
    _i13.Product? product,
    List<_i14.DownloadTask>? tasks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskOf,
          [
            product,
            tasks,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i14.DownloadTask?);
}

/// A class which mocks [SessionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionsRepository extends _i1.Mock
    implements _i15.SessionsRepository {
  @override
  _i6.Dio get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeDio_5(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeDio_5(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i6.Dio);

  @override
  _i3.CurrentUserRepository get currentUserRepository => (super.noSuchMethod(
        Invocation.getter(#currentUserRepository),
        returnValue: _FakeCurrentUserRepository_2(
          this,
          Invocation.getter(#currentUserRepository),
        ),
        returnValueForMissingStub: _FakeCurrentUserRepository_2(
          this,
          Invocation.getter(#currentUserRepository),
        ),
      ) as _i3.CurrentUserRepository);

  @override
  List<_i16.ProductPack> get audioPacks => (super.noSuchMethod(
        Invocation.getter(#audioPacks),
        returnValue: <_i16.ProductPack>[],
        returnValueForMissingStub: <_i16.ProductPack>[],
      ) as List<_i16.ProductPack>);

  @override
  List<_i16.ProductPack> get scriptPacks => (super.noSuchMethod(
        Invocation.getter(#scriptPacks),
        returnValue: <_i16.ProductPack>[],
        returnValueForMissingStub: <_i16.ProductPack>[],
      ) as List<_i16.ProductPack>);

  @override
  List<_i16.ProductPack> get audioWithScriptPacks => (super.noSuchMethod(
        Invocation.getter(#audioWithScriptPacks),
        returnValue: <_i16.ProductPack>[],
        returnValueForMissingStub: <_i16.ProductPack>[],
      ) as List<_i16.ProductPack>);

  @override
  List<_i13.Product> get audios => (super.noSuchMethod(
        Invocation.getter(#audios),
        returnValue: <_i13.Product>[],
        returnValueForMissingStub: <_i13.Product>[],
      ) as List<_i13.Product>);

  @override
  List<_i13.Product> get scripts => (super.noSuchMethod(
        Invocation.getter(#scripts),
        returnValue: <_i13.Product>[],
        returnValueForMissingStub: <_i13.Product>[],
      ) as List<_i13.Product>);

  @override
  _i4.Future<void> init(_i7.Session? session) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [session],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.Session> getOfflineSessionForDownloadedProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineSessionForDownloadedProducts,
          [],
        ),
        returnValue: _i4.Future<_i7.Session>.value(_FakeSession_6(
          this,
          Invocation.method(
            #getOfflineSessionForDownloadedProducts,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i7.Session>.value(_FakeSession_6(
          this,
          Invocation.method(
            #getOfflineSessionForDownloadedProducts,
            [],
          ),
        )),
      ) as _i4.Future<_i7.Session>);

  @override
  _i4.Future<_i7.Session> getSession() => (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [],
        ),
        returnValue: _i4.Future<_i7.Session>.value(_FakeSession_6(
          this,
          Invocation.method(
            #getSession,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i7.Session>.value(_FakeSession_6(
          this,
          Invocation.method(
            #getSession,
            [],
          ),
        )),
      ) as _i4.Future<_i7.Session>);

  @override
  _i4.Future<void> writeAudiosToBox(List<_i13.Product>? audios) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAudiosToBox,
          [audios],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> writeScriptsToBox(List<_i13.Product>? scripts) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeScriptsToBox,
          [scripts],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> writeRecentAudiosToBox(List<_i13.Product>? audios) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeRecentAudiosToBox,
          [audios],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> writeAudioPacksToBox(List<_i16.ProductPack>? audioPacks) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAudioPacksToBox,
          [audioPacks],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> writeScriptPacksToBox(List<_i16.ProductPack>? scriptPacks) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeScriptPacksToBox,
          [scriptPacks],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> writeAudioWithScriptPacksToBox(
          List<_i16.ProductPack>? audioWithScriptPacks) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAudioWithScriptPacksToBox,
          [audioWithScriptPacks],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [PlaylistsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistsRepository extends _i1.Mock
    implements _i17.PlaylistsRepository {
  @override
  _i6.Dio get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeDio_5(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeDio_5(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i6.Dio);

  @override
  _i2.Box<_i8.Playlist> get playlistsBox => (super.noSuchMethod(
        Invocation.getter(#playlistsBox),
        returnValue: _FakeBox_0<_i8.Playlist>(
          this,
          Invocation.getter(#playlistsBox),
        ),
        returnValueForMissingStub: _FakeBox_0<_i8.Playlist>(
          this,
          Invocation.getter(#playlistsBox),
        ),
      ) as _i2.Box<_i8.Playlist>);

  @override
  _i3.CurrentUserRepository get currentUserRepository => (super.noSuchMethod(
        Invocation.getter(#currentUserRepository),
        returnValue: _FakeCurrentUserRepository_2(
          this,
          Invocation.getter(#currentUserRepository),
        ),
        returnValueForMissingStub: _FakeCurrentUserRepository_2(
          this,
          Invocation.getter(#currentUserRepository),
        ),
      ) as _i3.CurrentUserRepository);

  @override
  _i4.Future<List<_i8.Playlist>> getPlaylists() => (super.noSuchMethod(
        Invocation.method(
          #getPlaylists,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Playlist>>.value(<_i8.Playlist>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i8.Playlist>>.value(<_i8.Playlist>[]),
      ) as _i4.Future<List<_i8.Playlist>>);

  @override
  _i4.Future<void> saveNewPlaylist({
    required String? name,
    required String? password,
    required String? playlistName,
    int? listNumber = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveNewPlaylist,
          [],
          {
            #name: name,
            #password: password,
            #playlistName: playlistName,
            #listNumber: listNumber,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deletePlaylist({
    required String? name,
    required String? password,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlaylist,
          [],
          {
            #name: name,
            #password: password,
            #id: id,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePlaylistName({
    required String? username,
    required String? password,
    required String? playlistName,
    required _i8.Playlist? playlist,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlaylistName,
          [],
          {
            #username: username,
            #password: password,
            #playlistName: playlistName,
            #playlist: playlist,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i13.Product?> getProductById(String? playlist) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [playlist],
        ),
        returnValue: _i4.Future<_i13.Product?>.value(),
        returnValueForMissingStub: _i4.Future<_i13.Product?>.value(),
      ) as _i4.Future<_i13.Product?>);

  @override
  _i4.Future<void> writePlaylistsToBox(List<_i8.Playlist>? playlists) =>
      (super.noSuchMethod(
        Invocation.method(
          #writePlaylistsToBox,
          [playlists],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> writePlaylistToBox(_i8.Playlist? playlist) =>
      (super.noSuchMethod(
        Invocation.method(
          #writePlaylistToBox,
          [playlist],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i8.Playlist> addToPlaylist(
    _i13.Product? audio,
    _i8.Playlist? playlist,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToPlaylist,
          [
            audio,
            playlist,
          ],
        ),
        returnValue: _i4.Future<_i8.Playlist>.value(_FakePlaylist_7(
          this,
          Invocation.method(
            #addToPlaylist,
            [
              audio,
              playlist,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i8.Playlist>.value(_FakePlaylist_7(
          this,
          Invocation.method(
            #addToPlaylist,
            [
              audio,
              playlist,
            ],
          ),
        )),
      ) as _i4.Future<_i8.Playlist>);

  @override
  _i4.Future<_i8.Playlist> removeFromPlaylist(
    _i13.Product? audio,
    _i8.Playlist? playlist,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromPlaylist,
          [
            audio,
            playlist,
          ],
        ),
        returnValue: _i4.Future<_i8.Playlist>.value(_FakePlaylist_7(
          this,
          Invocation.method(
            #removeFromPlaylist,
            [
              audio,
              playlist,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i8.Playlist>.value(_FakePlaylist_7(
          this,
          Invocation.method(
            #removeFromPlaylist,
            [
              audio,
              playlist,
            ],
          ),
        )),
      ) as _i4.Future<_i8.Playlist>);

  @override
  _i4.Future<_i8.Playlist> updatePlaylistEntry({
    required String? username,
    required String? password,
    required _i8.Playlist? playlist,
    required List<_i13.Product>? products,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlaylistEntry,
          [],
          {
            #username: username,
            #password: password,
            #playlist: playlist,
            #products: products,
          },
        ),
        returnValue: _i4.Future<_i8.Playlist>.value(_FakePlaylist_7(
          this,
          Invocation.method(
            #updatePlaylistEntry,
            [],
            {
              #username: username,
              #password: password,
              #playlist: playlist,
              #products: products,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i8.Playlist>.value(_FakePlaylist_7(
          this,
          Invocation.method(
            #updatePlaylistEntry,
            [],
            {
              #username: username,
              #password: password,
              #playlist: playlist,
              #products: products,
            },
          ),
        )),
      ) as _i4.Future<_i8.Playlist>);
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i18.ProductsRepository {
  @override
  _i6.Dio get httpClient => (super.noSuchMethod(
        Invocation.getter(#httpClient),
        returnValue: _FakeDio_5(
          this,
          Invocation.getter(#httpClient),
        ),
        returnValueForMissingStub: _FakeDio_5(
          this,
          Invocation.getter(#httpClient),
        ),
      ) as _i6.Dio);

  @override
  _i4.Future<List<_i13.Product>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue: _i4.Future<List<_i13.Product>>.value(<_i13.Product>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i13.Product>>.value(<_i13.Product>[]),
      ) as _i4.Future<List<_i13.Product>>);

  @override
  _i13.Product? getProductById(String? playlist) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [playlist],
        ),
        returnValueForMissingStub: null,
      ) as _i13.Product?);
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i9.AudioPlayer {
  @override
  _i9.PlaybackEvent get playbackEvent => (super.noSuchMethod(
        Invocation.getter(#playbackEvent),
        returnValue: _FakePlaybackEvent_8(
          this,
          Invocation.getter(#playbackEvent),
        ),
        returnValueForMissingStub: _FakePlaybackEvent_8(
          this,
          Invocation.getter(#playbackEvent),
        ),
      ) as _i9.PlaybackEvent);

  @override
  _i4.Stream<_i9.PlaybackEvent> get playbackEventStream => (super.noSuchMethod(
        Invocation.getter(#playbackEventStream),
        returnValue: _i4.Stream<_i9.PlaybackEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.PlaybackEvent>.empty(),
      ) as _i4.Stream<_i9.PlaybackEvent>);

  @override
  _i4.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i4.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration?>.empty(),
      ) as _i4.Stream<Duration?>);

  @override
  _i9.ProcessingState get processingState => (super.noSuchMethod(
        Invocation.getter(#processingState),
        returnValue: _i9.ProcessingState.idle,
        returnValueForMissingStub: _i9.ProcessingState.idle,
      ) as _i9.ProcessingState);

  @override
  _i4.Stream<_i9.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i4.Stream<_i9.ProcessingState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.ProcessingState>.empty(),
      ) as _i4.Stream<_i9.ProcessingState>);

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<bool> get playingStream => (super.noSuchMethod(
        Invocation.getter(#playingStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get volumeStream => (super.noSuchMethod(
        Invocation.getter(#volumeStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  double get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get speedStream => (super.noSuchMethod(
        Invocation.getter(#speedStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  double get pitch => (super.noSuchMethod(
        Invocation.getter(#pitch),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  _i4.Stream<double> get pitchStream => (super.noSuchMethod(
        Invocation.getter(#pitchStream),
        returnValue: _i4.Stream<double>.empty(),
        returnValueForMissingStub: _i4.Stream<double>.empty(),
      ) as _i4.Stream<double>);

  @override
  bool get skipSilenceEnabled => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<bool> get skipSilenceEnabledStream => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabledStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  Duration get bufferedPosition => (super.noSuchMethod(
        Invocation.getter(#bufferedPosition),
        returnValue: _FakeDuration_9(
          this,
          Invocation.getter(#bufferedPosition),
        ),
        returnValueForMissingStub: _FakeDuration_9(
          this,
          Invocation.getter(#bufferedPosition),
        ),
      ) as Duration);

  @override
  _i4.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<_i9.IcyMetadata?> get icyMetadataStream => (super.noSuchMethod(
        Invocation.getter(#icyMetadataStream),
        returnValue: _i4.Stream<_i9.IcyMetadata?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.IcyMetadata?>.empty(),
      ) as _i4.Stream<_i9.IcyMetadata?>);

  @override
  _i9.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _FakePlayerState_10(
          this,
          Invocation.getter(#playerState),
        ),
        returnValueForMissingStub: _FakePlayerState_10(
          this,
          Invocation.getter(#playerState),
        ),
      ) as _i9.PlayerState);

  @override
  _i4.Stream<_i9.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i4.Stream<_i9.PlayerState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.PlayerState>.empty(),
      ) as _i4.Stream<_i9.PlayerState>);

  @override
  _i4.Stream<List<_i9.IndexedAudioSource>?> get sequenceStream =>
      (super.noSuchMethod(
        Invocation.getter(#sequenceStream),
        returnValue: _i4.Stream<List<_i9.IndexedAudioSource>?>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<_i9.IndexedAudioSource>?>.empty(),
      ) as _i4.Stream<List<_i9.IndexedAudioSource>?>);

  @override
  _i4.Stream<List<int>?> get shuffleIndicesStream => (super.noSuchMethod(
        Invocation.getter(#shuffleIndicesStream),
        returnValue: _i4.Stream<List<int>?>.empty(),
        returnValueForMissingStub: _i4.Stream<List<int>?>.empty(),
      ) as _i4.Stream<List<int>?>);

  @override
  _i4.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i4.Stream<int?>.empty(),
        returnValueForMissingStub: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<_i9.SequenceState?> get sequenceStateStream => (super.noSuchMethod(
        Invocation.getter(#sequenceStateStream),
        returnValue: _i4.Stream<_i9.SequenceState?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.SequenceState?>.empty(),
      ) as _i4.Stream<_i9.SequenceState?>);

  @override
  bool get hasNext => (super.noSuchMethod(
        Invocation.getter(#hasNext),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasPrevious => (super.noSuchMethod(
        Invocation.getter(#hasPrevious),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.LoopMode get loopMode => (super.noSuchMethod(
        Invocation.getter(#loopMode),
        returnValue: _i9.LoopMode.off,
        returnValueForMissingStub: _i9.LoopMode.off,
      ) as _i9.LoopMode);

  @override
  _i4.Stream<_i9.LoopMode> get loopModeStream => (super.noSuchMethod(
        Invocation.getter(#loopModeStream),
        returnValue: _i4.Stream<_i9.LoopMode>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.LoopMode>.empty(),
      ) as _i4.Stream<_i9.LoopMode>);

  @override
  bool get shuffleModeEnabled => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<bool> get shuffleModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabledStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<int?> get androidAudioSessionIdStream => (super.noSuchMethod(
        Invocation.getter(#androidAudioSessionIdStream),
        returnValue: _i4.Stream<int?>.empty(),
        returnValueForMissingStub: _i4.Stream<int?>.empty(),
      ) as _i4.Stream<int?>);

  @override
  _i4.Stream<_i9.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
        Invocation.getter(#positionDiscontinuityStream),
        returnValue: _i4.Stream<_i9.PositionDiscontinuity>.empty(),
        returnValueForMissingStub:
            _i4.Stream<_i9.PositionDiscontinuity>.empty(),
      ) as _i4.Stream<_i9.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling => (super.noSuchMethod(
        Invocation.getter(#automaticallyWaitsToMinimizeStalling),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
        Invocation.getter(#canUseNetworkResourcesForLiveStreamingWhilePaused),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  double get preferredPeakBitRate => (super.noSuchMethod(
        Invocation.getter(#preferredPeakBitRate),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  bool get allowsExternalPlayback => (super.noSuchMethod(
        Invocation.getter(#allowsExternalPlayback),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get webSinkId => (super.noSuchMethod(
        Invocation.getter(#webSinkId),
        returnValue: _i19.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
        returnValueForMissingStub: _i19.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
      ) as String);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_9(
          this,
          Invocation.getter(#position),
        ),
        returnValueForMissingStub: _FakeDuration_9(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  _i4.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPositionStream,
          [],
          {
            #steps: steps,
            #minPeriod: minPeriod,
            #maxPeriod: maxPeriod,
          },
        ),
        returnValue: _i4.Stream<Duration>.empty(),
        returnValueForMissingStub: _i4.Stream<Duration>.empty(),
      ) as _i4.Stream<Duration>);

  @override
  _i4.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUrl,
          [url],
          {
            #headers: headers,
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilePath,
          [filePath],
          {
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAsset,
          [assetPath],
          {
            #package: package,
            #preload: preload,
            #initialPosition: initialPosition,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setAudioSource(
    _i9.AudioSource? source, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [source],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClip,
          [],
          {
            #start: start,
            #end: end,
            #tag: tag,
          },
        ),
        returnValue: _i4.Future<Duration?>.value(),
        returnValueForMissingStub: _i4.Future<Duration?>.value(),
      ) as _i4.Future<Duration?>);

  @override
  _i4.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSkipSilenceEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setSkipSilenceEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLoopMode(_i9.LoopMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setLoopMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setShuffleModeEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setShuffleModeEnabled,
          [enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> shuffle() => (super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAutomaticallyWaitsToMinimizeStalling(
          bool? automaticallyWaitsToMinimizeStalling) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutomaticallyWaitsToMinimizeStalling,
          [automaticallyWaitsToMinimizeStalling],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
          bool? canUseNetworkResourcesForLiveStreamingWhilePaused) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
          [canUseNetworkResourcesForLiveStreamingWhilePaused],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredPeakBitRate,
          [preferredPeakBitRate],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAllowsExternalPlayback,
          [allowsExternalPlayback],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seek(
    Duration? position, {
    int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
          {#index: index},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAndroidAudioAttributes(
          _i20.AndroidAudioAttributes? audioAttributes) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAndroidAudioAttributes,
          [audioAttributes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWebCrossOrigin(_i9.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWebCrossOrigin,
          [webCrossOrigin],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWebSinkId(String? webSinkId) => (super.noSuchMethod(
        Invocation.method(
          #setWebSinkId,
          [webSinkId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i21.Connectivity {
  @override
  _i4.Stream<List<_i22.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<List<_i22.ConnectivityResult>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<_i22.ConnectivityResult>>.empty(),
      ) as _i4.Stream<List<_i22.ConnectivityResult>>);

  @override
  _i4.Future<List<_i22.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i4.Future<List<_i22.ConnectivityResult>>.value(
            <_i22.ConnectivityResult>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i22.ConnectivityResult>>.value(
                <_i22.ConnectivityResult>[]),
      ) as _i4.Future<List<_i22.ConnectivityResult>>);
}
