name: error_handling
description: Dart package which manages error handling.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0