default_platform(:ios)

FLAVOR_NAME=ENV["FLAVOR_NAME"]
VERSION_NUMBER=ENV["VERSION_NUMBER"] ||= "1.0"

TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
GIT_AUTHORIZATION=ENV["GIT_AUTHORIZATION"]

APP_ID = ENV["APP_ID"]
APP_STORE_ID = ENV["APP_STORE_ID"]
APP_STORE_CONNECT_TEAM_ID = ENV["APP_STORE_CONNECT_TEAM_ID"]
PROVISIONING_PROFILE_SPECIFIER = "match Appstore #{APP_ID}"
APP_STORE_API_KEY_ID=ENV["APP_STORE_API_KEY_ID"]
APP_STORE_API_KEY_ISSUER=ENV["APP_STORE_API_KEY_ISSUER"]
APP_STORE_API_KEY_CONTENT=ENV["APP_STORE_API_KEY_CONTENT"]
TESTER_GROUP_IOS_NAME = ENV["TESTER_GROUP_IOS_NAME"]
FIREBASE_APP_ID = ENV["FIREBASE_APP_ID"]

platform :ios do
  def api_key
    # Check if APP_STORE_API_KEY_ID is provided and not empty
    if !ENV['APP_STORE_API_KEY_ID'].nil? && !ENV['APP_STORE_API_KEY_ID'].empty?
      app_store_connect_api_key(
        key_id: "#{APP_STORE_API_KEY_ID}",
        issuer_id: "#{APP_STORE_API_KEY_ISSUER}",
        duration: 1200, # maximum
        key_content: "#{APP_STORE_API_KEY_CONTENT}",
        is_key_content_base64: true,
      )
    end
  end

  desc "Submit a new build"
  lane :preRelease do
    raise_error_if_environment_variables_not_set

    increment_version

    prepare_code_signing
    build_ios_app_as_ipa

    is_external_testing = TESTER_GROUP_IOS_NAME != "Developers"

    upload_to_testflight(
	    distribute_external: is_external_testing,
	    expire_previous_builds: false,
	    skip_waiting_for_build_processing: true,
	    skip_submission: true,
	    ipa: "Runner.ipa",
	    groups: TESTER_GROUP_IOS_NAME, # This does not seem to work, at least when skip_waiting_for_build_processing: true is set. So we use distribute_external param instead.
      changelog: "Version #{VERSION_NUMBER}.#{current_build_number + 1}",
	  )

    commit_version_change
  end

  def raise_error_if_environment_variables_not_set
    if ENV['APP_ID'].nil? || ENV['APP_ID'].empty?
      # Raise user-friendly error
      UI.user_error!("It looks like environmental variables are not configured. Set them in GitHub Actions secrets.")
    end
  end

  lane :increment_version do
    build_number = current_build_number + 1
    set_build_number value: build_number
    set_version_number value: build_number
  end

	lane :prepare_code_signing do
    if !ENV['APP_STORE_API_KEY_ID'].nil? && !ENV['APP_STORE_API_KEY_ID'].empty?
      keychain_name = TEMP_KEYCHAIN_USER
      keychain_password = TEMP_KEYCHAIN_PASSWORD
      ensure_temp_keychain(keychain_name, keychain_password)

      match(
        type: 'appstore',
        app_identifier: "#{APP_ID}",
        git_basic_authorization: Base64.strict_encode64("#{GIT_AUTHORIZATION}"),
        keychain_name: keychain_name,
        keychain_password: keychain_password,
        api_key: api_key
      )
    else
      get_certificates
      get_provisioning_profile
    end
	end

  lane :build_ios_app_as_ipa do
    if !ENV['APP_STORE_API_KEY_ID'].nil? && !ENV['APP_STORE_API_KEY_ID'].empty?
      gym_options = {
        workspace: "Runner.xcworkspace",
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                APP_STORE_ID => PROVISIONING_PROFILE_SPECIFIER
            }
        },
        output_directory: '.',
      }
      
      gym_options[:scheme] = FLAVOR_NAME unless FLAVOR_NAME.nil? || FLAVOR_NAME.empty?
      
      gym(**gym_options)
    else
      # Cannot use `flutter build ipa` because of "CocoaPods is installed but broken. Skipping pod install." error
      scheme_to_use = FLAVOR_NAME.nil? || FLAVOR_NAME.empty? ? "Runner" : FLAVOR_NAME
      
      build_ios_app(scheme: scheme_to_use)
    end
  end

	def ensure_temp_keychain(name, password)
    delete_temp_keychain(name)
    create_temp_keychain(name, password)
  end

  def delete_temp_keychain(name)
    delete_keychain(
      name: name
    ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  end

  def create_temp_keychain(name, password)
    create_keychain(
      name: name,
      password: password,
      unlock: false,
      timeout: 0
    )
  end

	lane :current_build_number do
    testflight_options = {
      app_identifier: "#{APP_ID}",
      team_id: "#{APP_STORE_CONNECT_TEAM_ID}"
    }

    # Add the api_key to the options hash if it's not nil
    testflight_options[:api_key] = api_key unless api_key.nil?

    # Call latest_testflight_build_number with the assembled options
    ios_build_number = latest_testflight_build_number(**testflight_options)

		[ios_build_number, android_version_from_gradle].max
	end

  lane :android_version_from_gradle do
    path = '../../android/app/build.gradle'
    re = /versionCode\s+(\d+)/ 
    s = File.read(path)
    s[re, 1].to_i
  end

  lane :set_build_number do |options|
    build_number = options[:value]
    increment_build_number(
      build_number: build_number,
    )
  end

  # Setting version number too, because analytics is based on it
  lane :set_version_number do |options|
    build_number = options[:value]
    version_number = "#{VERSION_NUMBER}.#{build_number}"
    increment_version_number(
      version_number: version_number
    )
  end

  lane :commit_version_change do
    versionCode = current_build_number
    commit_version_bump(
      message: "iOS Version Bump to #{versionCode}",
      force: true,
      xcodeproj: "../ios/Runner.xcodeproj",
    )
    add_git_tag(build_number: versionCode)
    sh("git pull")
    push_to_git_remote
  end
end